export const FETCH_ENTRIES_FAILURE = 'FETCH_ENTRIES_FAILURE';
export const FETCH_ENTRIES_REQUEST = 'FETCH_ENTRIES_REQUEST';
export const FETCH_ENTRIES_SUCCESS = 'FETCH_ENTRIES_SUCCESS';
export const FETCH_VIEWERS_FAILURE = 'FETCH_VIEWERS_FAILURE';
export const FETCH_VIEWERS_REQUEST = 'FETCH_VIEWERS_REQUEST';
export const FETCH_VIEWERS_SUCCESS = 'FETCH_VIEWERS_SUCCESS';
export const MARK_ENTRY_AS_VIEWED = 'MARK_ENTRY_AS_VIEWED';
